# Tarea 02. Covid

In [1]:
# Carga de librerías pandas y geopandas.

import pandas as pd
import pandas as gpd

In [11]:
# Obtener versión de geopandas
gpd.__version__

'1.4.4'

## Carga de datos de Covid

In [24]:
# Carga de los datos 05_30_22_CSV_GENERAL
## Se coloca sep=";", para la división de columnas por medio de ;
general = gpd.read_csv("datos/05_30_22_CSV_GENERAL.csv", sep=";")

In [25]:
# Desplegar datos de general
general

,FECHA,SE,positivos,nue_posi,conf_lab,conf_nexo,muj_posi,hom_posi,extranj_posi,costar_posi,...,CEACOINS_UCI,CEACOINS_SALON,PAUT_UCI,PAUT_SALON,HVITO_UCI,HVITO_SALON,UNICAR_SAL,UNICAR_UCI,ARS-SIQ_SAL,ARS_SIQ_UCI
0,06/03/2020,10,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,07/03/2020,10,7,5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,08/03/2020,11,10,3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,09/03/2020,11,12,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10/03/2020,11,13,1,NaN,NaN,7.0,6.0,3.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,26/05/2022,21,896712,3499,3272.0,227.0,460886.0,435826.0,102478.0,794234.0,...,0.0,0.0,0.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0
812,27/05/2022,21,899404,2692,2491.0,201.0,462372.0,437032.0,102727.0,796677.0,...,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0
813,28/05/2022,21,901542,2138,1907.0,231.0,463595.0,437947.0,103010.0,798532.0,...,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0
814,29/05/2022,22,903213,1671,1603.0,68.0,464547.0,438666.0,103241.0,799972.0,...,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0
815,30/05/2022,22,904934,1721,1648.0,73.0,465503.0,439431.0,103460.0,801474.0,...,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0